### ISSUE TITLE
Automation Service Call 

### ISSUE THREAD

**Issue by macray76** [megakid/ha_octopus_intelligent#7]
Executing the select_option service to set the target ready time does not work for half past the hour settings. 

My test code looks like this... 
```
service: select.select_option
data:
  option: "08:30"
target:
  entity_id: select.octopus_target_ready_by_time
```

Automation runs but the time is set to 08:00 instead.

Exactly the same code works if setting "09:00" for example. Feels like it is ignoring the :30 part.
